# Generated by Django 4.1.2 on 2022-11-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places_app.post'),
        ),
    ]
