# Generated by Django 4.1.2 on 2022-11-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0003_images_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='x',
            field=models.DecimalField(decimal_places=14, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='y',
            field=models.DecimalField(decimal_places=14, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
