# Generated by Django 4.1.2 on 2022-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0004_post_x_post_y_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_title',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
