# Generated by Django 4.1.3 on 2022-11-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0006_alter_images_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
