# Generated by Django 4.1.3 on 2022-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0008_alter_images_options_images_number_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
