# Generated by Django 4.1.3 on 2022-11-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0009_alter_images_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
    ]
