# Generated by Django 4.1.3 on 2022-11-29 14:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0011_alter_post_description_short_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
