# Generated by Django 4.1.3 on 2022-11-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0012_alter_post_description_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='y',
            new_name='longitude',
        ),
    ]
