# Generated by Django 4.1.3 on 2022-11-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0013_rename_x_post_latitude_rename_y_post_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
