# Generated by Django 4.1.3 on 2022-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0016_alter_images_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
